In [12]:
import numpy as np
import pandas as pd
import os

In [13]:
df = pd.read_csv(
    "/Users/priyankaramachandran/Desktop/ML Project/dataset/sp500_stocks.csv"
)
print(df.columns.tolist())
print("-" * 80)

['Date', 'Symbol', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']
--------------------------------------------------------------------------------

In [14]:
# sort stocks by date
stocks = df.sort_values("Date")
stocks.head()

,Date,Symbol,Adj Close,Close,High,Low,Open,Volume
0,2010-01-04,MMM,44.016731,69.414719,69.774246,69.12207,69.473244,3640265.0
1729512,2010-01-04,ULTA,18.641415,18.850000,19.250000,18.59000,19.230000,594700.0
1051272,2010-01-04,KHC,NaN,NaN,NaN,NaN,NaN,NaN
1047504,2010-01-04,KLAC,21.911167,36.919998,37.369999,36.57000,36.599998,2827000.0
1043736,2010-01-04,KKR,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
stocks["Date"] = pd.to_datetime(stocks["Date"])
stocks = stocks.drop_duplicates(subset=["Date", "Symbol"], keep="first")


price_matrix = stocks.pivot(index="Date", columns="Symbol", values="Close").sort_index()
print("Pivoted price matrix shape:", price_matrix.shape)
display(price_matrix.head())


full_dates = pd.date_range(
    start=price_matrix.index.min(), end=price_matrix.index.max(), freq="B"
)
price_matrix = price_matrix.reindex(full_dates)
price_matrix.index.name = "Date"
print("Shape after setting common date range:", price_matrix.shape)

missing_counts = price_matrix.isna().sum().sort_values(ascending=False)
print("Missing values per ticker (top 20):")
display(missing_counts.head(20))
missing_counts.to_csv("missing_counts.csv")

print("Number of tickers with zero NaNs:", (missing_counts == 0).sum())


total_days = price_matrix.shape[0]
missing_percent = (missing_counts / total_days) * 100
valid_tickers = missing_percent[missing_percent <= 5].index
cleaned_prices = price_matrix[valid_tickers]

print(
    f"Kept {len(valid_tickers)} tickers out of {price_matrix.shape[1]} after filtering >5% missing."
)

output_dir = "/Users/priyankaramachandran/Desktop/ML Project/dataset/"
os.makedirs(output_dir, exist_ok=True)

cleaned_prices.to_csv(os.path.join(output_dir, "cleaned_data.csv"), index=True)
print("Cleaned price matrix saved successfully as CSV!")

Pivoted price matrix shape: (3768, 502)

Symbol,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,22.389128,7.643214,NaN,NaN,26.129908,7.994444,42.070000,37.090000,31.670000,31.469999,...,70.913910,44.279999,63.959999,21.080000,69.150002,NaN,25.226456,58.271847,28.670000,NaN
2010-01-05,22.145924,7.656429,NaN,NaN,25.918797,7.967778,42.330002,37.700001,31.620001,31.639999,...,70.754967,45.220001,67.849998,20.830000,69.419998,NaN,25.140186,60.116505,28.620001,NaN
2010-01-06,22.067240,7.534643,NaN,NaN,26.062737,7.933333,42.779999,37.619999,31.559999,31.559999,...,71.894043,44.720001,66.959999,20.870001,70.019997,NaN,24.960461,60.097088,28.400000,NaN
2010-01-07,22.038628,7.520714,NaN,NaN,26.278646,7.886667,42.740002,36.889999,31.309999,31.230000,...,71.682121,44.520000,68.389999,20.780001,69.800003,NaN,24.953272,61.475727,27.690001,NaN
2010-01-08,22.031473,7.570714,NaN,NaN,26.412991,7.871111,42.570000,36.689999,31.490000,30.840000,...,71.602646,44.110001,67.900002,20.790001,69.519997,NaN,24.960461,60.184467,27.600000,NaN

Shape after setting common date range: (3905, 502)
Missing values per ticker (top 20):

Symbol
AMTM    3842
SW      3787
GEV     3720
SOLV    3720
VLTO    3598
KVUE    3493
GEHC    3398
CEG     3169
ABNB    2891
PLTR    2841
OTIS    2706
CARR    2706
CRWD    2512
CTVA    2500
UBER    2490
DOW     2454
FOX     2449
FOXA    2448
MRNA    2385
DAY     2229
dtype: int64

Number of tickers with zero NaNs: 0
Kept 432 tickers out of 502 after filtering >5% missing.
Cleaned price matrix saved successfully as CSV!

In [16]:
price_matrix

Symbol,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,22.389128,7.643214,NaN,NaN,26.129908,7.994444,42.070000,37.090000,31.670000,31.469999,...,70.913910,44.279999,63.959999,21.080000,69.150002,NaN,25.226456,58.271847,28.670000,NaN
2010-01-05,22.145924,7.656429,NaN,NaN,25.918797,7.967778,42.330002,37.700001,31.620001,31.639999,...,70.754967,45.220001,67.849998,20.830000,69.419998,NaN,25.140186,60.116505,28.620001,NaN
2010-01-06,22.067240,7.534643,NaN,NaN,26.062737,7.933333,42.779999,37.619999,31.559999,31.559999,...,71.894043,44.720001,66.959999,20.870001,70.019997,NaN,24.960461,60.097088,28.400000,NaN
2010-01-07,22.038628,7.520714,NaN,NaN,26.278646,7.886667,42.740002,36.889999,31.309999,31.230000,...,71.682121,44.520000,68.389999,20.780001,69.800003,NaN,24.953272,61.475727,27.690001,NaN
2010-01-08,22.031473,7.570714,NaN,NaN,26.412991,7.871111,42.570000,36.689999,31.490000,30.840000,...,71.602646,44.110001,67.900002,20.790001,69.519997,NaN,24.960461,60.184467,27.600000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-16,137.669998,251.039993,171.630005,132.199997,112.620003,91.339996,357.059998,461.529999,216.309998,51.689999,...,313.149994,29.650000,89.680000,67.660004,108.470001,120.779999,135.050003,106.849998,406.899994,175.809998
2024-12-17,136.460007,253.479996,175.380005,132.240005,113.290001,90.529999,357.299988,455.230011,213.820007,51.490002,...,310.529999,29.379999,91.959999,68.080002,108.010002,120.769997,134.729996,108.059998,395.000000,170.789993
2024-12-18,133.009995,248.050003,173.020004,127.540001,111.930000,88.709999,347.609985,441.309998,207.770004,49.849998,...,307.549988,27.959999,88.699997,66.400002,106.419998,116.919998,131.460007,105.860001,383.470001,167.009995
2024-12-19,133.190002,249.789993,171.520004,129.350006,112.419998,88.989998,372.160004,437.390015,207.779999,49.380001,...,311.000000,27.209999,88.309998,66.650002,105.510002,116.430000,130.360001,105.809998,385.369995,163.520004
2024-12-20,134.509995,254.490005,175.580002,134.210007,114.230003,90.989998,366.369995,447.170013,211.779999,50.490002,...,317.570007,27.500000,88.949997,67.400002,105.870003,117.139999,132.360001,107.120003,393.040009,164.839996