In [206]:
import numpy as np
import pandas as pd

In [207]:
data = pd.read_csv("./dataset/cleaned_data.csv", index_col="Date")

In [208]:
data.index = pd.to_datetime(data.index)

In [209]:
prices = data.copy()
prices = prices.sort_index()
print("Price matrix shape:", prices.shape)
display(prices.head())

Price matrix shape: (3905, 432)

,GNRC,CHTR,MTCH,NDAQ,WFC,WM,WELL,WMB,MU,NDSN,...,EXPE,EXPD,EXC,EW,EVRG,ETR,ETN,ESS,ES,IT
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,12.84,35.0,5.856653,6.746667,27.320000,34.160000,44.040001,17.616472,10.85,31.530001,...,51.639999,35.080002,34.864479,7.289167,21.840000,41.075001,32.160000,82.620003,25.770000,18.700001
2010-01-05,12.84,35.0,5.985151,6.766667,28.070000,34.009998,44.660000,17.836576,11.17,31.490000,...,51.860001,35.320000,34.293865,7.341667,21.549999,40.419998,31.969999,83.120003,25.680000,18.730000
2010-01-06,12.84,35.0,5.936608,6.763333,28.110001,34.000000,44.439999,18.415367,11.22,31.139999,...,49.200001,34.500000,34.500713,7.422500,21.670000,40.625000,31.830000,83.699997,26.010000,18.860001
2010-01-07,12.84,35.0,5.965163,6.673333,29.129999,34.080002,44.529999,18.284937,10.84,31.514999,...,48.939999,34.290001,34.614838,7.490000,21.530001,40.139999,32.299999,84.570000,25.969999,20.440001
2010-01-08,12.84,33.5,6.002284,6.743333,28.860001,34.240002,44.070000,18.431671,11.10,31.875000,...,48.480000,34.650002,34.450787,7.456667,21.719999,39.755001,33.025002,83.699997,26.040001,20.660000

In [210]:
print(prices.dtypes)

GNRC    float64
CHTR    float64
MTCH    float64
NDAQ    float64
WFC     float64
         ...
ETR     float64
ETN     float64
ESS     float64
ES      float64
IT      float64
Length: 432, dtype: object

In [211]:
print(prices.isna().sum())

GNRC    0
CHTR    0
MTCH    0
NDAQ    0
WFC     0
       ..
ETR     0
ETN     0
ESS     0
ES      0
IT      0
Length: 432, dtype: int64

In [212]:
returns = prices.pct_change()
log_returns = np.log(prices / prices.shift(1))

In [213]:
returns.columns = [c + "_ret" for c in returns.columns]
log_returns.columns = [c + "_logret" for c in log_returns.columns]

In [214]:
returns.head()

,GNRC_ret,CHTR_ret,MTCH_ret,NDAQ_ret,WFC_ret,WM_ret,WELL_ret,WMB_ret,MU_ret,NDSN_ret,...,EXPE_ret,EXPD_ret,EXC_ret,EW_ret,EVRG_ret,ETR_ret,ETN_ret,ESS_ret,ES_ret,IT_ret
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,0.0,0.000000,0.021940,0.002964,0.027452,-0.004391,0.014078,0.012494,0.029493,-0.001269,...,0.004260,0.006841,-0.016367,0.007203,-0.013278,-0.015947,-0.005908,0.006052,-0.003492,0.001604
2010-01-06,0.0,0.000000,-0.008111,-0.000493,0.001425,-0.000294,-0.004926,0.032450,0.004476,-0.011115,...,-0.051292,-0.023216,0.006032,0.011010,0.005568,0.005072,-0.004379,0.006978,0.012850,0.006941
2010-01-07,0.0,0.000000,0.004810,-0.013307,0.036286,0.002353,0.002025,-0.007083,-0.033868,0.012042,...,-0.005285,-0.006087,0.003308,0.009094,-0.006461,-0.011938,0.014766,0.010394,-0.001538,0.083775
2010-01-08,0.0,-0.042857,0.006223,0.010489,-0.009269,0.004695,-0.010330,0.008025,0.023985,0.011423,...,-0.009399,0.010499,-0.004739,-0.004450,0.008825,-0.009591,0.022446,-0.010287,0.002695,0.010763

In [215]:
log_returns.head()

,GNRC_logret,CHTR_logret,MTCH_logret,NDAQ_logret,WFC_logret,WM_logret,WELL_logret,WMB_logret,MU_logret,NDSN_logret,...,EXPE_logret,EXPD_logret,EXC_logret,EW_logret,EVRG_logret,ETR_logret,ETN_logret,ESS_logret,ES_logret,IT_logret
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,0.0,0.000000,0.021703,0.002960,0.027082,-0.004401,0.013980,0.012417,0.029067,-0.001269,...,0.004251,0.006818,-0.016502,0.007177,-0.013367,-0.016075,-0.005925,0.006034,-0.003499,0.001603
2010-01-06,0.0,0.000000,-0.008144,-0.000493,0.001424,-0.000294,-0.004938,0.031934,0.004466,-0.011177,...,-0.052654,-0.023490,0.006014,0.010950,0.005553,0.005059,-0.004389,0.006954,0.012769,0.006917
2010-01-07,0.0,0.000000,0.004799,-0.013396,0.035643,0.002350,0.002023,-0.007108,-0.034455,0.011970,...,-0.005299,-0.006106,0.003302,0.009053,-0.006481,-0.012010,0.014658,0.010341,-0.001539,0.080450
2010-01-08,0.0,-0.043803,0.006204,0.010435,-0.009312,0.004684,-0.010384,0.007993,0.023702,0.011358,...,-0.009444,0.010444,-0.004751,-0.004460,0.008786,-0.009638,0.022198,-0.010341,0.002692,0.010706

In [216]:
prices.head()

,GNRC,CHTR,MTCH,NDAQ,WFC,WM,WELL,WMB,MU,NDSN,...,EXPE,EXPD,EXC,EW,EVRG,ETR,ETN,ESS,ES,IT
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,12.84,35.0,5.856653,6.746667,27.320000,34.160000,44.040001,17.616472,10.85,31.530001,...,51.639999,35.080002,34.864479,7.289167,21.840000,41.075001,32.160000,82.620003,25.770000,18.700001
2010-01-05,12.84,35.0,5.985151,6.766667,28.070000,34.009998,44.660000,17.836576,11.17,31.490000,...,51.860001,35.320000,34.293865,7.341667,21.549999,40.419998,31.969999,83.120003,25.680000,18.730000
2010-01-06,12.84,35.0,5.936608,6.763333,28.110001,34.000000,44.439999,18.415367,11.22,31.139999,...,49.200001,34.500000,34.500713,7.422500,21.670000,40.625000,31.830000,83.699997,26.010000,18.860001
2010-01-07,12.84,35.0,5.965163,6.673333,29.129999,34.080002,44.529999,18.284937,10.84,31.514999,...,48.939999,34.290001,34.614838,7.490000,21.530001,40.139999,32.299999,84.570000,25.969999,20.440001
2010-01-08,12.84,33.5,6.002284,6.743333,28.860001,34.240002,44.070000,18.431671,11.10,31.875000,...,48.480000,34.650002,34.450787,7.456667,21.719999,39.755001,33.025002,83.699997,26.040001,20.660000

In [217]:
rolling_mean = prices.rolling(window=20).mean()
rolling_std = prices.rolling(window=20).std()

In [218]:
rolling_mean.columns = [c + "_rollmean20" for c in rolling_mean.columns]
rolling_std.columns = [c + "_rollstd20" for c in rolling_std.columns]

In [219]:
rolling_mean.head(5)

,GNRC_rollmean20,CHTR_rollmean20,MTCH_rollmean20,NDAQ_rollmean20,WFC_rollmean20,WM_rollmean20,WELL_rollmean20,WMB_rollmean20,MU_rollmean20,NDSN_rollmean20,...,EXPE_rollmean20,EXPD_rollmean20,EXC_rollmean20,EW_rollmean20,EVRG_rollmean20,ETR_rollmean20,ETN_rollmean20,ESS_rollmean20,ES_rollmean20,IT_rollmean20
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [220]:
rolling_std.head()

,GNRC_rollstd20,CHTR_rollstd20,MTCH_rollstd20,NDAQ_rollstd20,WFC_rollstd20,WM_rollstd20,WELL_rollstd20,WMB_rollstd20,MU_rollstd20,NDSN_rollstd20,...,EXPE_rollstd20,EXPD_rollstd20,EXC_rollstd20,EW_rollstd20,EVRG_rollstd20,ETR_rollstd20,ETN_rollstd20,ESS_rollstd20,ES_rollstd20,IT_rollstd20
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [221]:
def compute_RSI(series: pd.Series, window=14):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.rolling(window).mean()
    avg_loss = loss.rolling(window).mean()

    RS = avg_gain / avg_loss
    RSI = 100 - (100 / (1 + RS))
    return RSI


rsi_df = pd.DataFrame(index=prices.index)

for col in prices.columns:
    rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)

/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)
/var/folders/zr/2wb4s69j7kl53vcr3tq54zpw0000gn/T/ipykernel_42806/3094679.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rsi_df[col + "_RSI14"] = compute_RSI(prices[col], 14)

In [222]:
rsi_df.head(20)

,GNRC_RSI14,CHTR_RSI14,MTCH_RSI14,NDAQ_RSI14,WFC_RSI14,WM_RSI14,WELL_RSI14,WMB_RSI14,MU_RSI14,NDSN_RSI14,...,EXPE_RSI14,EXPD_RSI14,EXC_RSI14,EW_RSI14,EVRG_RSI14,ETR_RSI14,ETN_RSI14,ESS_RSI14,ES_RSI14,IT_RSI14
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-22,NaN,0.0,49.738218,20.125822,49.520771,35.227274,43.702562,54.730996,29.620842,28.393962,...,8.757644,44.588739,34.301534,64.127767,44.890498,34.690424,55.199989,43.297365,44.561377,72.709166
2010-01-25,NaN,0.0,40.730404,18.849899,46.531304,34.675618,38.980258,57.117750,27.560965,29.603524,...,6.611564,42.729279,35.683466,64.903851,51.004039,40.112503,52.010060,43.601516,47.535222,74.003808
2010-01-26,NaN,0.0,42.274083,17.507476,41.437301,34.140974,38.916262,46.350375,28.605750,30.215836,...,19.240508,50.663121,37.656903,61.201698,48.319329,41.051646,51.460526,39.551106,39.382226,73.449623
2010-01-27,NaN,0.0,43.909363,25.074707,43.090652,33.258913,41.232215,45.931274,36.206893,26.024786,...,19.638254,55.645146,34.652096,57.664248,47.325081,42.543027,45.989980,40.153266,42.264158,63.563823
2010-01-28,NaN,0.0,39.664877,19.384732,46.944861,27.766155,43.500002,41.918299,29.368917,18.406581,...,18.627457,45.358051,34.231765,54.576841,40.677998,39.345693,38.496720,41.065842,39.179072,61.126788
2010-01-29,NaN,0.0,34.626093,16.811666,47.226396,20.362016,40.549280,37.165335,26.304342,18.389744,...,18.357488,40.992122,27.500026,41.421776,32.692324,27.556787,21.149609,35.897437,33.207568,61.299434

In [223]:
feature_matrix = pd.concat(
    [
        prices,
        returns,
        log_returns,
        rolling_mean,
        rolling_std,
        rsi_df,
    ],
    axis=1,
)

In [224]:
feature_matrix.head()

,GNRC,CHTR,MTCH,NDAQ,WFC,WM,WELL,WMB,MU,NDSN,...,EXPE_RSI14,EXPD_RSI14,EXC_RSI14,EW_RSI14,EVRG_RSI14,ETR_RSI14,ETN_RSI14,ESS_RSI14,ES_RSI14,IT_RSI14
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,12.84,35.0,5.856653,6.746667,27.320000,34.160000,44.040001,17.616472,10.85,31.530001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,12.84,35.0,5.985151,6.766667,28.070000,34.009998,44.660000,17.836576,11.17,31.490000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-06,12.84,35.0,5.936608,6.763333,28.110001,34.000000,44.439999,18.415367,11.22,31.139999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-07,12.84,35.0,5.965163,6.673333,29.129999,34.080002,44.529999,18.284937,10.84,31.514999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-08,12.84,33.5,6.002284,6.743333,28.860001,34.240002,44.070000,18.431671,11.10,31.875000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [225]:
feature_matrix.to_csv("./dataset/features.csv", index=True)